### ISSUE TITLE
mbquartR: Finding Manitoba Quarter Sections

### ISSUE THREAD

**Issue by alex-koiter** [ropensci/software-review#658]
**Date accepted:** 2025-03-04

Submitting Author Name: Alexander Koiter
Submitting Author Github Handle: @alex-koiter
Other Package Authors Github handles: (comma separated, delete if none) 
Repository:  https://github.com/alex-koiter/mbquartR
Version submitted:  0.0.0.9000
Submission type: Standard
Editor: @jhollist
Reviewers: @sheilasaia, @emilymarkowitz-noaa
Due date for @emilymarkowitz-noaa: 2024-12-11
Archive: TBD
Version accepted: TBD
Language: en

---

-   Paste the full DESCRIPTION file inside a code block below:

Package: mbquartR
Title: Finding Manitoba Quarter Sections
Version: 0.0.0.9000
Authors@R: 
    person("Alex", "Koiter", , "koitera@brandonu.ca", role = c("aut", "cre"),
           comment = c(ORCID = "0000-0002-9355-9561"))
Description: This package has three main functions: 1) find the coordinates of a quarter sections given the legal land description (e.g., "NE-11-33-29W"); 2) find the legal land description using coordinates (lat and long); and 3) plot these points on a map. 
License: MIT + file LICENSE
URL: http://alexkoiter.ca/mbquartR/, https://github.com/alex-koiter/mbquartR
BugReports: https://github.com/alex-koiter/mbquartR/issues
Encoding: UTF-8
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.3.1
Suggests: 
    testthat (>= 3.0.0),
    curl (>= 5.2.1),
    knitr,
    rmarkdown
Config/testthat/edition: 3
Imports: 
    dplyr (>= 1.1.4),
    purrr (>= 1.0.2),
    sf (>= 1.0.16),
    tibble (>= 3.2.1),
    tidyr (>= 1.3.1),
    stringr (>= 1.5.1),
    units (>= 0.8.5),
    mapview (>= 2.11.2),
    readr (>= 2.1.4),
    crayon (>= 1.5.2),
    rlang
VignetteBuilder: knitr
```

```

## Scope

- Please indicate which category or categories from our [package fit policies](https://ropensci.github.io/dev_guide/policies.html#package-categories) this package falls under: (Please check an appropriate box below. If you are unsure, we suggest you make a pre-submission inquiry.):

	- [x] data retrieval
	- [x] data extraction
	- [ ] data munging
	- [ ] data deposition
    - [ ] data validation and testing
	- [ ] workflow automation
	- [ ] version control
	- [ ] citation management and bibliometrics
	- [ ] scientific software wrappers
	- [ ] field and lab reproducibility tools
	- [ ] database software bindings
	- [ ] geospatial data
	- [ ] text analysis

- Explain how and why the package falls under these categories (briefly, 1-2 sentences):

This package enables users to download the Manitoba Original Survey Legal Descriptions data from the Manitoba government geoportal. It includes functions that allow users to easily search for parcels of land (i.e., quarter sections) by either the legal land description or by coordinates and plot them on an interactive map.

-   Who is the target audience and what are scientific applications of this package?

The target audience are those who work with geospatial data in Manitoba, particularly those who are working with rural or farm parcels of land where the legal land description is commonly used as the method of identifying the location. Also anyone who needs to quickly go back and forth between geographic coordinates and the legal land description. Currently, there are a few web-based tools (https://geoportal.gov.mb.ca/datasets/11fa11f9015b45438d6493dcb3d8071c/, https://www.masc.mb.ca/masc.nsf/land_parcel_info.html, https://legallandconverter.com/p4.html) that allow users to locate land parcels but do not allow for batch processing, do not return coordinates, and/or are fee based. Being able to convert back and forth is also helpful for scientist preparing outreach materials.

-   Are there other R packages that accomplish the same thing? If so, how does yours differ or meet [our criteria for best-in-category](https://ropensci.github.io/dev_guide/policies.html#overlap)?

No

-   (If applicable) Does your package comply with our [guidance around _Ethics, Data Privacy and Human Subjects Research_](https://devguide.ropensci.org/policies.html#ethics-data-privacy-and-human-subjects-research)?

NA. This package provides access to publicly available data.

-   If you made a pre-submission inquiry, please paste the link to the corresponding issue, forum post, or other discussion, or @tag the editor you contacted.

https://github.com/ropensci/software-review/issues/649

-   Explain reasons for any [`pkgcheck` items](https://docs.ropensci.org/pkgcheck/) which your package is unable to pass.

`pkgcheck` passes fully with github actions but fails locally because it doesn't think I have CI (but I do).

## Technical checks

Confirm each of the following by checking the box.

- [x] I have read the [rOpenSci packaging guide](https://devguide.ropensci.org/building.html).
- [x] I have read the [author guide](https://devdevguide.netlify.app/authors-guide.html) and I expect to maintain this package for at least 2 years or to find a replacement.

This package:

- [x] does not violate the Terms of Service of any service it interacts with.
- [x] has a CRAN and OSI accepted license.
- [x] contains a [README with instructions for installing the development version](https://ropensci.github.io/dev_guide/building.html#readme).
- [x] includes [documentation with examples for all functions, created with roxygen2](https://ropensci.github.io/dev_guide/building.html#documentation).
- [x] contains a vignette with examples of its essential functions and uses.
- [x] has a [test suite](https://ropensci.github.io/dev_guide/building.html#testing).
- [x] has [continuous integration](https://ropensci.github.io/dev_guide/ci.html), including reporting of test coverage.

## Publication options

- [ ] Do you intend for this package to go on CRAN?
- [ ] Do you intend for this package to go on Bioconductor?

- [ ] Do you wish to submit an Applications Article about your package to [Methods in Ecology and Evolution](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/)? If so:

<details>
<summary>MEE Options</summary>

- [ ] The package is novel and will be of interest to the broad readership of the journal.
- [ ] The manuscript describing the package is no longer than 3000 words.
- [ ] You intend to archive the code for the package in a long-term repository which meets the requirements of the journal (see [MEE's Policy on Publishing Code](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/journal-resources/policy-on-publishing-code.html))
- (*Scope: Do consider MEE's [Aims and Scope](http://besjournals.onlinelibrary.wiley.com/hub/journal/10.1111/(ISSN)2041-210X/aims-and-scope/read-full-aims-and-scope.html) for your manuscript. We make no guarantee that your manuscript will be within MEE scope.*)
- (*Although not required, we strongly recommend having a full manuscript prepared when you submit here.*)
- (*Please do not submit your package separately to Methods in Ecology and Evolution*)

</details>

## Code of conduct

- [x] I agree to abide by [rOpenSci's Code of Conduct](https://ropensci.org/code-of-conduct/) during the review process and in maintaining my package should it be accepted.

**Comment by adamhsparks** [comment]
Hi @alex-koiter, the rOpenSci bot says this is all good, but when I run checks locally, I get an error.

```r
> devtools::check()
══ Documenting ════════════════════════════════════════════════════════════════════════════
ℹ Installed roxygen2 version (7.3.2) doesn't match required (7.3.1)
✖ `check()` will not re-document this package
══ Building ═══════════════════════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
── R CMD build ────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/Users/adamsparks/tmp/mbquartR/DESCRIPTION’ ...
─  preparing ‘mbquartR’:
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
E  creating vignettes (1.5s)
   --- re-building ‘mbquartR.Rmd’ using rmarkdown
   
   Quitting from lines 69-71 [example] (mbquartR.Rmd)
   Error: processing vignette 'mbquartR.Rmd' failed with diagnostics:
   Data doesn't exist, please download with `quarters_dl()` first
   --- failed re-building ‘mbquartR.Rmd’
   
   SUMMARY: processing the following file failed:
     ‘mbquartR.Rmd’
   
   Error: Vignette re-building failed.
   Execution halted
Error:
! ! System command 'R' failed
Show Traceback
```

Please ignore the roxygen2 comment, I'm concerned about the Error creating vignettes.

**Comment by alex-koiter** [comment]
Thanks @adamhsparks! The issue was that the vignette needed to access data that hadn't been downloaded yet. I have now created some sample data that the vignette uses. Also found some additional typos and made a few other small changes. It should work now.

**Comment by adamhsparks** [comment]
Looks good, @alex-koiter. Thanks, I'll proceed from here.

**Comment by adamhsparks** [comment]
@ropensci-review-bot assign @jhollist as editor

**Comment by jhollist** [comment]
@alex-koiter I will take some time today/tomorrow to dig into this a bit and will get back to you with any suggestions.  Looking forward to the review process!

**Comment by jhollist** [comment]
@alex-koiter I am just now starting to look at this (apologies!!)  I still get the the same error as @adamhsparks with the vignette build.  I have cloned and attempted to build https://github.com/alex-koiter/mbquartR and get the error. Perhaps the fix wasn't pushed?

Also I see no documentation on your non-exported functions (Statistical Properties in https://github.com/ropensci/software-review/issues/658#issuecomment-2366968970).  While not technically required, it would be  an easy area of improvement to add documentation on these non-exported functions.

**Comment by alex-koiter** [comment]
@jhollist It turns out that I only partially resolved the issue (or fixed a different one). I have resolved the error so you should be able to clone and build the package now. I will take me a few days to get the documentation for the internal functions completed and I will let you know once that is done.
Thanks!

**Comment by jhollist** [comment]
And FYI, check runs now on my machine!  I did see this:

---
─  checking examples ... [43s] OK (43.4s)
   Examples with CPU (user + system) or elapsed time > 5s
                 user system elapsed
   map_quarter  23.53   2.08   28.48
   search_coord 10.39   0.65    8.47
---
I know this is system specific so might not be a real issue, but if there is an easy way to have the example run a bit faster that would be good.

**Comment by alex-koiter** [comment]
@jhollist The internal function documentation is now complete. As for the run time, I think this may be an artifact of how the functions are written. This is where the reviewers may be able to provide some suggestions.
Thanks!

**Comment by jhollist** [comment]
@alex-koiter Thanks!  Looks good on my end.  Will start looking for reviewers now.

**Comment by jhollist** [comment]
@ropensci-review-bot assign @sheilasaia as reviewer

**Comment by jhollist** [comment]
@ropensci-review-bot assign @emilymarkowitz-noaa as reviewer

**Comment by EmilyMarkowitz-NOAA** [comment]
---
title: "review"
output: 
  rmarkdown::md_document:
    pandoc_args: [
      "--wrap=none"
    ]
---

## Package Review

*Please check off boxes as applicable, and elaborate in comments below.  Your review is not limited to these topics, as described in the reviewer guide*

- **Briefly describe any working relationship you have (had) with the package authors.**
- [x] As the reviewer I confirm that there are no [conflicts of interest](https://devguide.ropensci.org/policies.html#coi) for me to review this work (if you are unsure whether you are in conflict, please speak to your editor _before_ starting your review).

#### Documentation

The package includes all the following forms of documentation:

- [X] **A statement of need:** clearly stating problems the software is designed to solve and its target audience in README
- [X] **Installation instructions:** for the development version of package and any non-standard dependencies in README
- [X] **Vignette(s):** demonstrating major functionality that runs successfully locally
- [X] **Function Documentation:** for all exported functions
- [X] **Examples:** (that run successfully locally) for all exported functions
- [X] **Community guidelines:** including contribution guidelines in the README or CONTRIBUTING, and DESCRIPTION with `URL`, `BugReports` and `Maintainer` (which may be autogenerated via `Authors@R`).

#### Functionality

- [X] **Installation:** Installation succeeds as documented. _See output below._
- [X] **Functionality:** Any functional claims of the software have been confirmed.
- [X] **Performance:** Any performance claims of the software have been confirmed.
- [ ] **Automated tests:** Unit tests cover essential functions of the package and a reasonable range of inputs and conditions. All tests pass on the local machine. _There are some issues with the tests, see output below._
- [ ] **Packaging guidelines**: The package conforms to the rOpenSci packaging guidelines.

Estimated hours spent reviewing: 3

- [ ] Should the author(s) deem it appropriate, I agree to be acknowledged as a package reviewer ("rev" role) in the package DESCRIPTION file.

_No need, but thanks for offering._
---

### Review Comments

In addition to agreeing with the first reviewer's comments, I have a few to add, which I've mostly left in the numbered bullets below. In general, and similarly to the other reviewer, I was able to install the R package, run the functions as expected, thought the package worked well and was well documented. Though this R Package has a very specific audience, it sounds like it will be an easy and helpful too for them. I share similar sentiments that the README could include more details and context and had the same errors with the test checks that the other reviewer had. 

Thanks for the opportunity to review and let me know if you have any questions! This is my first time reviewing an R package for ROpenSci, so please let me know if there is anything I missed or forgot to cover. Good luck, and hope this helps! Thanks for making a package to help the folks of Manitoba! 

1. Readme could include more information about the institution, author ([example](https://github.com/afsc-gap-products/gap_products?tab=readme-ov-file#this-code-is-primarally-maintained-by)), additional resources, the government legal (example [1](https://github.com/afsc-gap-products/gap_products?tab=readme-ov-file#access-constraints), [2](https://github.com/afsc-gap-products/gap_products?tab=readme-ov-file#noaa-license)), and access constraints to this data ([example](https://github.com/afsc-gap-products/gap_products?tab=readme-ov-file#access-constraints)). I've included links here to a repository I'm working on at NOAA for reference. 
2. The first reviewer made a great note about maintainer redundancy. Possibly related to or fixed by stating your affiliation (as I noted above), but sharing more about who you are and your/your affiliation's commitment to this package would help users know its priority for upkeep to maintainers and who might take over if you pass the package along to someone else to maintain.  
3. It may be worthwhile to choose a licence like the GNU General Public Licence v3.0 or MIT Licence for your work, rather than just the two "YEAR" and "COPYWRITE HOLDER" lines. They're fine, but its my understanding that the ones I mentioned are standard practice and are recommended at my organization. 
4. Cite the contributor guide (a `CONTRIBUTING.md`) on your README. It took me a minute to find in your pkgdown site. It may be worthwhile to also add some other types of contributor guidelines, like those from repos we use at [NOAA](https://github.com/nmfs-opensci/Contributor-Guide) (pruely for reference). 
5. Possibly add a summary map of Manitoba with all of the different areas to it, so users can get a sense for the breadth of what the R Package covers. As a user unfamiliar with Manitoba's quarter sections system, I had to make some assumptions about what "quarters" meant and how they were used (is it the same thing as or related to [this](https://en.wikipedia.org/wiki/Dominion_Land_Survey)?). 
6. Some of the bullets appear to be a bit messed up on this [page](https://alexkoiter.ca/mbquartR/reference/mbquartR-package.html). Also, I think the contents of this page could be added directly to a new or as a summary at the top of the [existing vingette](https://alexkoiter.ca/mbquartR/articles/mbquartR.html). 
7. The [`quarters_dl()` example](https://alexkoiter.ca/mbquartR/reference/quarters_dl.html#arguments) seems to be a bit misprinted and I think would benefit from a . I think you want to use `\dontrun{}` like this: 

```
#'@examples
#'\dontrun{
#'geocode("3817 Spruce St, Philadelphia, PA 19104")
#'geocode("Philadelphia, PA")
#'dat <- data.frame(value=runif(3),address=c("3817 Spruce St, Philadelphia, PA 19104","Philadelphia, PA","Neverneverland"))
#'geocode(dat)
#'}
```
8. In general, there are a few sentences throughout the documentation that don't end with periods ("."). 
9. I agree with the other reviewer's second comment. I'll add to that by noting: Specify the bounds and data type in the [`search_coords()` arguments examples](https://alexkoiter.ca/mbquartR/reference/search_coord.html#arguments). Perhaps something like `Numeric. Latitude (decimal degree) with resolution up to one hundred thousandth of a degree. Values outside of bounds will return error (49 to 59.5°N). ` I added the resolution and the "will return error" ideas in there, feel free to use or do something different. I used the general boundaries of manatoba here, for example. 
10. In the `search_legal` function, I would add a link to where a user can look up the legal land descriptions. 
11. Add more information and a citation for the [open data source](https://geoportal.gov.mb.ca) you are using. The only place I found it listed was in the [function file](https://github.com/alex-koiter/mbquartR/blob/6fd24396898b0c3e1f4ad2ffb772c3a29d3a2fca/R/download.R#L101-L102).
12. In addition to the other reviewer's 5th comment, it would be great to include a section that 1) identifies work that has used this package and 2) create a vingette of a specific example with storyline using this package (e.g., "A farmer wants to know ..."). Some of the content provided in the ROpenSci application could be helpful for this. 
13. A package like this seems ripe for an R Shiny app - something that can be interactive for the non-coder. Just something to consider in a next stage of the package's development. 
14. Seconding the first reviewer's comment 6). I am also not familiar with the legal land descriptions in Manitoba, but the examples provided in the vignette worked well for me without any errors.
15.  The first reviewer made a great point to ask how often the package data will be upated. It would be good to note this in the documentation for users so they can anticipate future changes.
16. See check run notes below. Specifically, I got two errors when I tried to run the package test: 

**A. "search_coord() returns dataframe"**
`q` is a `tibble()`, not a dataframe
```
-- Error: search_coord() returns dataframe -------------------------------------
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    x
 1. \-testthat::expect_equal(...)
 2.   \-testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     \-testthat:::waldo_compare(...)
 4.       \-waldo::compare(tolerance = NULL)
 5.         \-waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           \-waldo:::.stop_not_number(...)
 7.             \-waldo:::stop_input_type(...)
 8.               \-rlang::abort(message, ..., call = call, arg = arg)

Error:
! Test failed
Backtrace:
    x
 1. +-testthat::test_that(...)
 2. | \-withr (local) `<fn>`()
 3. \-reporter$stop_if_needed()
 4.   \-rlang::abort("Test failed", call = NULL)
```

**B. "search_legal() returns dataframe**
`q` is a `tibble()`, not a dataframe
```
-- Error: search_legal() returns dataframe -------------------------------------
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    x
 1. \-testthat::expect_equal(...)
 2.   \-testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     \-testthat:::waldo_compare(...)
 4.       \-waldo::compare(tolerance = NULL)
 5.         \-waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           \-waldo:::.stop_not_number(...)
 7.             \-waldo:::stop_input_type(...)
 8.               \-rlang::abort(message, ..., call = call, arg = arg)

Error:
! Test failed
Backtrace:
    x
 1. +-testthat::test_that(...)
 2. | \-withr (local) `<fn>`()
 3. \-reporter$stop_if_needed()
 4.   \-rlang::abort("Test failed", call = NULL)
```

#### Check runs

<details>
<summary>R Session Info</summary>
<br>

`sessionInfo()`

```
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_United States.utf8  LC_CTYPE=English_United States.utf8    LC_MONETARY=English_United States.utf8
[4] LC_NUMERIC=C                           LC_TIME=English_United States.utf8    

time zone: America/Los_Angeles
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mbquartR_0.0.0.9000

loaded via a namespace (and not attached):
 [1] miniUI_0.1.1.1    compiler_4.4.1    promises_1.3.2    Rcpp_1.0.13-1     rcmdcheck_1.4.0   callr_3.7.6       later_1.4.1      
 [8] fastmap_1.2.0     mime_0.12         R6_2.5.1          curl_6.0.1        htmlwidgets_1.6.4 tibble_3.2.1      desc_1.4.3       
[15] profvis_0.4.0     rprojroot_2.0.4   shiny_1.9.1       pillar_1.9.0      rlang_1.1.4       utf8_1.2.4        cachem_1.1.0     
[22] httpuv_1.6.15     fs_1.6.5          pkgload_1.4.0     memoise_2.0.1     cli_3.6.3         withr_3.0.2       magrittr_2.0.3   
[29] ps_1.8.1          processx_3.8.4    digest_0.6.37     rstudioapi_0.17.1 xtable_1.8-4      remotes_2.5.0     devtools_2.4.5   
[36] lifecycle_1.0.4   prettyunits_1.2.0 vctrs_0.6.5       glue_1.8.0        xopen_1.0.1       urlchecker_1.0.1  sessioninfo_1.2.2
[43] pkgbuild_1.4.5    fansi_1.0.6       purrr_1.0.2       tools_4.4.1       usethis_3.1.0     pkgconfig_2.0.3   ellipsis_0.3.2   
[50] htmltools_0.5.8.1
```
</details>


<details>
<summary>Clean and install: success</summary>
<br>

```
==> Rcmd.exe INSTALL --preclean --no-multiarch --with-keep.source mbquartR

* installing to library 'C:/Users/emily.markowitz/AppData/Local/R/win-library/4.4'
* installing *source* package 'mbquartR' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (mbquartR)
```

</details>


<details>
<summary>Devtools output: 1 error (from test checks)</summary>
<br>

`devtools::check()`

```
══ Documenting ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
ℹ Installed roxygen2 version (7.3.2) doesn't match required (7.3.1)
✖ `check()` will not re-document this package
══ Building ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Setting env vars:
• CFLAGS    : -Wall -pedantic -fdiagnostics-color=always
• CXXFLAGS  : -Wall -pedantic -fdiagnostics-color=always
• CXX11FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX14FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX17FLAGS: -Wall -pedantic -fdiagnostics-color=always
• CXX20FLAGS: -Wall -pedantic -fdiagnostics-color=always
── R CMD build ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\emily.markowitz\Work\projects\mbquartR/DESCRIPTION' (455ms)
─  preparing 'mbquartR':
✔  checking DESCRIPTION meta-information ...
─  installing the package to build vignettes
✔  creating vignettes (19.9s)
─  checking for LF line-endings in source and make files and shell scripts (1.2s)
─  checking for empty or unneeded directories
─  building 'mbquartR_0.0.0.9000.tar.gz'
   
══ Checking ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Setting env vars:
• _R_CHECK_CRAN_INCOMING_REMOTE_               : FALSE
• _R_CHECK_CRAN_INCOMING_                      : FALSE
• _R_CHECK_FORCE_SUGGESTS_                     : FALSE
• _R_CHECK_PACKAGES_USED_IGNORE_UNUSED_IMPORTS_: FALSE
• NOT_CRAN                                     : true
── R CMD check ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
─  using log directory 'C:/Users/emily.markowitz/AppData/Local/Temp/Rtmpy80E8v/file56a01c33567f/mbquartR.Rcheck' (505ms)
─  using R version 4.4.1 (2024-06-14 ucrt)
─  using platform: x86_64-w64-mingw32
─  R was compiled by
       gcc.exe (GCC) 13.2.0
       GNU Fortran (GCC) 13.2.0
─  running under: Windows 10 x64 (build 19045)
─  using session charset: UTF-8
─  using options '--no-manual --as-cran'
✔  checking for file 'mbquartR/DESCRIPTION'
─  this is package 'mbquartR' version '0.0.0.9000'
─  package encoding: UTF-8
✔  checking package namespace information
✔  checking package dependencies (1.6s)
✔  checking if this is a source package ...
✔  checking if there is a namespace
✔  checking for executable files (1.3s)
✔  checking for hidden files and directories ...
✔  checking for portable file names
✔  checking serialization versions
✔  checking whether package 'mbquartR' can be installed (6.2s)
✔  checking installed package size (461ms)
✔  checking package directory (570ms)
✔  checking for future file timestamps ... 
✔  checking 'build' directory ...
✔  checking DESCRIPTION meta-information (730ms)
✔  checking top-level files
✔  checking for left-over files ...
✔  checking index information (458ms)
✔  checking package subdirectories (1.1s)
✔  checking code files for non-ASCII characters ... 
✔  checking R files for syntax errors ... 
✔  checking whether the package can be loaded (668ms)
✔  checking whether the package can be loaded with stated dependencies (440ms)
✔  checking whether the package can be unloaded cleanly (549ms)
✔  checking whether the namespace can be loaded with stated dependencies (449ms)
✔  checking whether the namespace can be unloaded cleanly (651ms)
✔  checking loading without being on the library search path (1s)
✔  checking whether startup messages can be suppressed (1.2s)
✔  checking dependencies in R code (7.3s)
✔  checking S3 generic/method consistency (661ms)
✔  checking replacement functions (549ms)
✔  checking foreign function calls (533ms)
✔  checking R code for possible problems (5.2s)
✔  checking Rd files (534ms)
✔  checking Rd metadata ... 
✔  checking Rd line widths ... 
✔  checking Rd cross-references (439ms)
✔  checking for missing documentation entries (551ms)
✔  checking for code/documentation mismatches (1.5s)
✔  checking Rd \usage sections (998ms)
✔  checking Rd contents ... 
✔  checking for unstated dependencies in examples (339ms)
✔  checking contents of 'data' directory ...
✔  checking data for non-ASCII characters (406ms)
✔  checking LazyData
✔  checking data for ASCII and uncompressed saves (395ms)
✔  checking installed files from 'inst/doc' (539ms)
✔  checking files in 'vignettes' (599ms)
─  checking examples ... [36s] OK (36.6s)
   Examples with CPU (user + system) or elapsed time > 5s
                 user system elapsed
   map_quarter  32.34   2.39   24.92
   search_coord 11.40   0.56    6.75
✔  checking for unstated dependencies in 'tests' ... 
─  checking tests ...
   Running the tests in 'tests/testthat.R' failed.
   Last 13 lines of output:
     Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
     Backtrace:
         ▆
      1. └─testthat::expect_equal(...) at test-search_legal.R:6:3
      2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
      3.     └─testthat:::waldo_compare(...)
      4.       └─waldo::compare(tolerance = NULL)
      5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
      6.           └─waldo:::.stop_not_number(...)
      7.             └─waldo:::stop_input_type(...)
      8.               └─rlang::abort(message, ..., call = call, arg = arg)
     
     [ FAIL 2 | WARN 1 | SKIP 0 | PASS 42 ]
     Error: Test failures
     Execution halted
✔  checking for unstated dependencies in vignettes (777ms)
✔  checking package vignettes ... 
─  checking re-building of vignette outputs ... [16s] OK (16.1s)
✔  checking for non-standard things in the check directory
✔  checking for detritus in the temp directory
   
   See
     'C:/Users/emily.markowitz/AppData/Local/Temp/Rtmpy80E8v/file56a01c33567f/mbquartR.Rcheck/00check.log'
   for details.
   
   
── R CMD check results ────────────────────────────────────────────────────────────────────────────────────────────────── mbquartR 0.0.0.9000 ────
Duration: 2m 50.7s

❯ checking tests ...
  See below...

── Test failures ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────── testthat ────

> # This file is part of the standard setup for testthat.
> # It is recommended that you do not modify it.
> #
> # Where should you do additional test configuration?
> # Learn more about the roles of various files in:
> # * https://r-pkgs.org/testing-design.html#sec-tests-files-overview
> # * https://testthat.r-lib.org/articles/special-files.html
> 
> library(testthat)
> library(mbquartR)
> 
> test_check("mbquartR")
[ FAIL 2 | WARN 1 | SKIP 0 | PASS 42 ]

══ Warnings ════════════════════════════════════════════════════════════════════
── Warning ('test-mapping.R:3:3'): map_quarter() returns a map ─────────────────
package 'mapview' was built under R version 4.4.2
Backtrace:
    ▆
 1. └─base::library(mapview) at test-mapping.R:3:3
 2.   └─base (local) testRversion(pkgInfo, package, pkgpath)

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-search_coord.R:6:3'): search_coord() returns dataframe ─────────
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    ▆
 1. └─testthat::expect_equal(...) at test-search_coord.R:6:3
 2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     └─testthat:::waldo_compare(...)
 4.       └─waldo::compare(tolerance = NULL)
 5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           └─waldo:::.stop_not_number(...)
 7.             └─waldo:::stop_input_type(...)
 8.               └─rlang::abort(message, ..., call = call, arg = arg)
── Error ('test-search_legal.R:6:3'): search_legal() returns dataframe ─────────
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    ▆
 1. └─testthat::expect_equal(...) at test-search_legal.R:6:3
 2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     └─testthat:::waldo_compare(...)
 4.       └─waldo::compare(tolerance = NULL)
 5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           └─waldo:::.stop_not_number(...)
 7.             └─waldo:::stop_input_type(...)
 8.               └─rlang::abort(message, ..., call = call, arg = arg)

[ FAIL 2 | WARN 1 | SKIP 0 | PASS 42 ]
Error: Test failures
Execution halted

1 error ✖ | 0 warnings ✔ | 0 notes ✔
```
</details>

<details>
<summary>Test checks: 2 errors</summary>
<br>

`devtools::test()`

```
ℹ Testing mbquartR
✔ | F W  S  OK | Context
✔ |         22 | download [30.9s]                                                                                                                 
⠏ |          0 | mapping                                                                                                                          GDAL version >= 3.1.0 | setting mapviewOptions(fgb = TRUE)
✔ |   1      5 | mapping [10.2s]                                                                                                                  
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Warning (test-mapping.R:3:3): map_quarter() returns a map
package 'mapview' was built under R version 4.4.2
Backtrace:
    ▆
 1. └─base::library(mapview) at test-mapping.R:3:3
 2.   └─base (local) testRversion(pkgInfo, package, pkgpath)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ | 1        8 | search_coord [7.0s]                                                                                                              
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-search_coord.R:6:3): search_coord() returns dataframe
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    ▆
 1. └─testthat::expect_equal(...) at test-search_coord.R:6:3
 2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     └─testthat:::waldo_compare(...)
 4.       └─waldo::compare(tolerance = NULL)
 5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           └─waldo:::.stop_not_number(...)
 7.             └─waldo:::stop_input_type(...)
 8.               └─rlang::abort(message, ..., call = call, arg = arg)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖ | 1        7 | search_legal [8.6s]                                                                                                              
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-search_legal.R:6:3): search_legal() returns dataframe
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    ▆
 1. └─testthat::expect_equal(...) at test-search_legal.R:6:3
 2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     └─testthat:::waldo_compare(...)
 4.       └─waldo::compare(tolerance = NULL)
 5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           └─waldo:::.stop_not_number(...)
 7.             └─waldo:::stop_input_type(...)
 8.               └─rlang::abort(message, ..., call = call, arg = arg)
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

══ Results ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
Duration: 59.5 s

── Failed tests ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Error (test-search_coord.R:6:3): search_coord() returns dataframe
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    ▆
 1. └─testthat::expect_equal(...) at test-search_coord.R:6:3
 2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     └─testthat:::waldo_compare(...)
 4.       └─waldo::compare(tolerance = NULL)
 5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           └─waldo:::.stop_not_number(...)
 7.             └─waldo:::stop_input_type(...)
 8.               └─rlang::abort(message, ..., call = call, arg = arg)

Error (test-search_legal.R:6:3): search_legal() returns dataframe
Error in `waldo::compare(x, y, ..., x_arg = x_arg, y_arg = y_arg)`: `tolerance` must be a number or `NULL`, not `TRUE`.
Backtrace:
    ▆
 1. └─testthat::expect_equal(...) at test-search_legal.R:6:3
 2.   └─testthat:::expect_waldo_equal("equal", act, exp, info, ..., tolerance = tolerance)
 3.     └─testthat:::waldo_compare(...)
 4.       └─waldo::compare(tolerance = NULL)
 5.         └─waldo:::check_number_decimal(tolerance, allow_null = TRUE, min = 0)
 6.           └─waldo:::.stop_not_number(...)
 7.             └─waldo:::stop_input_type(...)
 8.               └─rlang::abort(message, ..., call = call, arg = arg)

[ FAIL 2 | WARN 1 | SKIP 0 | PASS 42 ]
```

</details>

**Comment by jhollist** [comment]
@sheilasaia and @EmilyMarkowitz-NOAA Thank you so much for your reviews! You are all set for now, but once @alex-koiter responds I will ask you to take a look at those responses and let me know if your comments were adequately addressed.  Also, keep a rough tally of the time you spent on the review and follow-ups.  We like to keep track of this.

@alex-koiter Please take a look at these reviews, ask any questions that arise, and work on the revisions. 

If there is anything I can do to help, just let me know.

Thanks again all!

**Comment by alex-koiter** [comment]
Thanks to @sheilasaia and @EmilyMarkowitz-NOAA for taking the time to review my package. Some good suggestions to implement. I will start working on this and if I have any questions or need clarification I will let you know.

**Comment by alex-koiter** [comment]
@jhollist I am also interested in submitting to JOSS. I know there is an opportunity to combine the rOpenSci review with the JOSS review process, is there anything in particular I should be aware of moving forward. I am currently preparing the paper.

**Comment by jhollist** [comment]
@alex-koiter I am not sure about the details on JOSS submission.  let me dig and get back to you.

**Comment by jhollist** [comment]
@alex-koiter A bit here on it: https://devguide.ropensci.org/softwarereview_author.html#preparing-for-submission.

I think we keep on with the track we are going on.  The JOSS side will happen after rOpenSci review.  The current EiC may coordinate this process.  I will find out.

In short, JOSS will make their own determination on scope and if it is in scope you will submit your paper.md for review with JOSS.  The package will not need a separate review.

**Comment by jhollist** [comment]
@alex-koiter It looks like all you will need to do is specify that the package been reviewed by rOpenSci during the pre-submisison phase with JOSS.  Here is an example issue: https://github.com/openjournals/joss-reviews/issues/6163#issuecomment-1888111491

**Comment by jhollist** [comment]
@alex-koiter Just checking in to see how edits are going and if there is anything you need from me at this point.

**Comment by alex-koiter** [comment]
@jhollist thanks for the check-in! Edits are going well. In addressing the reviewer comments I found a few other items/issues that needed to be addressed/fixed. The code/functionality of the package has been updated and is working as expected, but I am still working on updating the documentation and tests.

**Comment by maurolepore** [comment]
Dear @alex-koiter and @jhollist this is just to mark the start of my EiC rotation and record what I see in case there is anything I can help with.

I see the author is still addressing reviewers' comments and the communication is fluid. I'll step back. Thanks!

**Comment by jhollist** [comment]
@alex-koiter First, apologies for the delay in responding.  Been a bit of a whirlwind these last couple of weeks...  

Nice job on the revisions.  Our next steps are to get concurrence from @EmilyMarkowitz-NOAA and @sheilasaia on the revisions.  Once the sign off, we are good to move on to the next steps.   

Thank everyone for your work on this!

**Comment by jhollist** [comment]
@ropensci-review-bot submit https://github.com/ropensci/software-review/issues/658#issuecomment-2510378080 review time 3

**Comment by jhollist** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/658#issuecomment-2510378080 time 3

**Comment by jhollist** [comment]
@ropensci-review-bot submit review https://github.com/ropensci/software-review/issues/658#issuecomment-2530238917 time 3

**Comment by alex-koiter** [comment]
@jhollist No worries about the short delay! I have more than enough to do to keep me busy :)

**Comment by jhollist** [comment]
@EmilyMarkowitz-NOAA and @sheilasaia, just following up to see if you have had a chance to look at the revisions.  You can let me know with a quick comment here if your suggestions have been addressed.

Thanks!

**Comment by EmilyMarkowitz-NOAA** [comment]
❇ I am happy with the changes, plus these comments:

13. Sounds good about the data source being listed in the `quarters_dl` function. If interested, it might be good to have a short list in the readme. If I am pulling data from another source I always try to put that front and center. Is there a link to the data page that could be included? Maybe something as simple as: 

>  Data Sources
> - The full list of quarter sections and coordinates are downloaded from the Manitoba Geoportal. Note that when the Geoportal is unavailable, data is downloaded from an archived version from the package repository on GitHub.

17. Weird that having leaflets in the reference pages is giving you trouble. In my quick search, I couldn't find an example where a leaflet output was used in the pkgdown 'Reference' section. I'll have to keep searching and will let you know if I find any examples to work/compare with. 

6. I still think a map of the extent would be nice (completely a suggestion -- you're right that it might be a bit pointless) to show the boundaries of the data available. Maybe something as simple as this (I just threw it together, so if interested, please make your own!): 

```
library(ggplot2)
library(sf)
library(maps)
library(rnaturalearth)

crs_out <- "EPSG:4326"
crs_in <- "+proj=longlat +datum=WGS84 +ellps=WGS84 +towgs84=0,0,0"

world_coordinates <- rnaturalearth::ne_states(c("canada", "united states of america"))  %>% 
  dplyr::mutate(fill = dplyr::case_when( 
    name_sv == "Manitoba" ~ "Manitoba",
    geonunit == "Canada" ~ "Canada",
    geonunit == "United States of America" ~ "USA")) %>% 
  sf::st_as_sf() %>%
  sf::st_transform(crs = crs_out) 

Manitoba <- world_coordinates %>% 
  dplyr::filter(fill == "Manitoba")

place_labels <- data.frame(
  type = c("country", "country", "providence"), 
  lab = c("United States", "Canada", "Manitoba"), 
  angle = c(0, 0, 0), 
  lat = c(46.405283, 52.105838, 55.989065), 
  lon = c(-99.180802, -86.535079, -96.966046)) %>%
  sf::st_as_sf(coords = c("lon", "lat"),
               crs = crs_in) %>%
  sf::st_transform(crs = crs_out) 

pp <- ggplot2::ggplot() +
  # plot shapes
  ggplot2::geom_sf(
    data = world_coordinates,
    mapping = aes(fill = fill), 
    show.legend = FALSE, 
    color = "grey20")  + 
  ggplot2::scale_fill_grey() +
  # add labels
  ggplot2::geom_sf_text(
    data = place_labels %>% dplyr::filter(type == "country"),
    mapping = aes(label = lab, angle = angle), 
    color = "grey40", 
    fontface = "bold",
    size = 5, 
    show.legend = FALSE) + 
  ggplot2::geom_sf_text(
    data = place_labels %>% dplyr::filter(type == "providence"),
    mapping = aes(label = lab, angle = angle), 
    color = "black",
    fontface = "bold",
    size = 6, 
    show.legend = FALSE) + 
  # Manage Axis extents (limits) and breaks
  ggplot2::scale_x_continuous(name = "Longitude °W",
                              breaks = seq(-120, -70, 5)) +
  ggplot2::scale_y_continuous(name = "Latitude °N",
                              breaks = seq(50, 65, 5)) + # seq(52, 62, 2) 
  ggplot2::coord_sf(xlim = c(sf::st_bbox(Manitoba)[1]-5, sf::st_bbox(Manitoba)[3]+5),
                    ylim = c(sf::st_bbox(Manitoba)[2]-5, sf::st_bbox(Manitoba)[4]+5)) +
  # themes
  ggplot2::theme_bw() +
  ggplot2::theme(
    plot.margin=unit(c(0,0,0,0), "cm"), 
    panel.border = element_rect(colour = "grey20", linewidth = .25, fill = NA),
    panel.background = element_rect(fill = "white"), 
    panel.grid = element_line(colour="grey80", linewidth = 0.5), 
    axis.text = element_text(face = "bold")
  )


pp
```
Which creates this: 

![Image](https://github.com/user-attachments/assets/ae447b1c-577d-48f7-8b82-bd04e66dc89f)

**Comment by alex-koiter** [comment]
@EmilyMarkowitz-NOAA Thanks for the suggestions. I just finished making the changes.
1. Data source now listed in the README
2. Map showing the location of Manitoba is now included in the README. I misinterpreted the map suggestion, as I thought the request was to map all the quarter sections :grinning:
3. Yes I also could not find an example of where `mapview::mapview()` was used, which makes me wonder if it is expected behaviour

**Comment by sheilasaia** [comment]
👍 I'm also happy with all the changes @alex-koiter made! Yes, Emily's map extent suggestion is exactly what I was thinking of....just in case folks need a geography refresher. 😊 

One last thing from me. Given Alex's and Emily's `map_quarter()` comments, I reinstalled from GitHub and when I run the code below, I'm not seeing the polygon lines in RStudio when I use `map_quarter()`. Am attaching an image of what I'm seeing and my session info. Maybe this is also related to the issue you're having for the pkgdown docs? I hope that I'm not missing something. My other thought was to ask @jhollist if he as any ideas on how to address the leaflet issue. 😄 

Other than that, it looks great to me! Thank you for this opportunity to review this cool package! 🗺 💻 🧭 

![Image](https://github.com/user-attachments/assets/c09ae9a3-f8da-44b5-8a1f-6327ee9bc8c6)

```
result <- search_coord(long = c(-101.4656, -99.99768, -101.4656), lat = c(51.81913, 49.928926, 51.81913))
map_quarter(result)
```

Session info:
```
> sessionInfo()
R version 4.4.2 (2024-10-31)
Platform: aarch64-apple-darwin20
Running under: macOS Sequoia 15.1.1

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mbquartR_0.0.0.9000 gert_2.1.4          pkgreviewr_0.3.1    pkgcheck_0.1.2.077 
[5] tictoc_1.2.1        fs_1.6.5            remotes_2.5.0      

loaded via a namespace (and not attached):
 [1] gtable_0.3.6            raster_3.6-31           ggplot2_3.5.1           htmlwidgets_1.6.4      
 [5] lattice_0.22-6          tzdb_0.4.0              leaflet.providers_2.0.0 vctrs_0.6.5            
 [9] tools_4.4.2             crosstalk_1.2.1         generics_0.1.3          stats4_4.4.2           
[13] parallel_4.4.2          tibble_3.2.1            proxy_0.4-27            pkgconfig_2.0.3        
[17] KernSmooth_2.23-26      satellite_1.0.5         leaflet_2.2.2           lifecycle_1.0.4        
[21] farver_2.1.2            compiler_4.4.2          stringr_1.5.1           credentials_2.0.2      
[25] munsell_0.5.1           terra_1.8-29            codetools_0.2-20        htmltools_0.5.8.1      
[29] sys_3.4.3               class_7.3-23            jquerylib_0.1.4         pillar_1.10.1          
[33] crayon_1.5.3            tidyr_1.3.1             openssl_2.3.2           classInt_0.4-11        
[37] wk_0.9.4                viridis_0.6.5           tidyselect_1.2.1        digest_0.6.37          
[41] stringi_1.8.4           sf_1.0-19               dplyr_1.1.4             purrr_1.0.4            
[45] fastmap_1.2.0           grid_4.4.2              colorspace_2.1-1        cli_3.6.4              
[49] magrittr_2.0.3          base64enc_0.1-3         utf8_1.2.4              leafem_0.2.3           
[53] e1071_1.7-16            readr_2.1.5             withr_3.0.2             scales_1.3.0           
[57] rappdirs_0.3.3          sp_2.2-0                bit64_4.6.0-1           bit_4.5.0.1            
[61] gridExtra_2.3           png_0.1-8               askpass_1.2.1           hms_1.1.3              
[65] mapview_2.11.2          viridisLite_0.4.2       s2_1.1.7                rlang_1.1.5            
[69] Rcpp_1.0.14             glue_1.8.0              DBI_1.2.3               jsonlite_1.9.0         
[73] rstudioapi_0.17.1       vroom_1.6.5             R6_2.6.1                units_0.8-5
```

**Comment by alex-koiter** [comment]
@sheilasaia thanks for reviewing the package again!
It looks like the polygons are in fact plotting, but you will need to zoom in on one of the points to see them. Quarter sections are very small given the size of the province. Quarter sections are only about 0.65 km<sup>2</sup>. Let me know if you can see the polygon if you zoom in on a point.

**Comment by jhollist** [comment]
@ropensci-review-bot approve mbquartR

**Comment by alex-koiter** [comment]
@ropensci-review-bot finalize transfer of mbquartR

**Comment by sheilasaia** [comment]
@alex-koiter got it! Now I understand why I wasn't seeing them. Congrats and thanks again for the opportunity to review this package.

**Comment by alex-koiter** [comment]
@sheilasaia and @EmilyMarkowitz-NOAA I would like your consent to acknowledge your help in making this package so much better in the package DESCRIPTION as reviewers. If you do consent could I please get your preferred spelling of your name.

Thanks!

**Comment by EmilyMarkowitz-NOAA** [comment]
So kind, @alex-koiter ! Thank you! Yes, here is my info: 

[Emily Markowitz](https://www.fisheries.noaa.gov/contact/emily-markowitz)
Research Fisheries Biologist, [Alaska Fisheries Science Center](https://www.fisheries.noaa.gov/alaska/science-data/groundfish-assessment-program-bottom-trawl-surveys)
NOAA Fisheries | U.S. Department of Commerce

Also: https://emilyhmarkowitz.github.io/emilyhmarkowitz

**Comment by sheilasaia** [comment]
Yes, that's very nice of you, @alex-koiter! Thanks so much! My info is below:

Sheila M. Saia, PhD
Environmental Data Scientist, Tetra Tech
https://sheilasaia.rbind.io/
